FROM registry.access.redhat.com/ubi8/ubi:8.5-214

ENV CONDA_HOME=${CONDA_HOME:-/opt/conda}
ENV PATH=$CONDA_HOME/bin:$PATH

ENV OPEN_CE_CONDA_BUILD=3.22.0
ENV OPEN_CE_CONDA=4.14

ENV CICD_GROUP=cicd
ARG GROUP_ID=1500
ENV BUILD_USER=builder
ARG BUILD_ID=1084

RUN export ARCH="$(uname -m)" && \
    yum repolist && yum install -y rsync openssh-clients diffutils procps git-lfs gcc-toolset-11 glibc-devel file libtirpc-devel psmisc libX11-devel && \
    # Create CICD Group
    groupadd --non-unique --gid ${GROUP_ID} ${CICD_GROUP} && \
    # Adduser Builder
    useradd -b /home --non-unique --create-home --gid ${GROUP_ID} --groups wheel \
    --uid ${BUILD_ID} --comment "User for Building" ${BUILD_USER} && \
    curl -o /tmp/anaconda.sh https://repo.anaconda.com/miniconda/Miniconda3-py310_22.11.1-1-Linux-${ARCH}.sh && \
    chmod +x /tmp/anaconda.sh && \
    /bin/bash /tmp/anaconda.sh -f -b -p /opt/conda && \
    rm -f /tmp/anaconda.sh && \
    $CONDA_HOME/bin/conda install -y conda-build=${OPEN_CE_CONDA_BUILD} conda=${OPEN_CE_CONDA} networkx git junit-xml patch && \
    $CONDA_HOME/bin/conda config --system --add envs_dirs $CONDA_HOME/envs && \
    $CONDA_HOME/bin/conda config --system --add pkgs_dirs $CONDA_HOME/pkgs && \
    $CONDA_HOME/bin/conda config --system --set always_yes true && \
    $CONDA_HOME/bin/conda config --system --set auto_update_conda false && \
    $CONDA_HOME/bin/conda config --system --set notify_outdated_conda false && \
    $CONDA_HOME/bin/conda --version && \
    mkdir -p $CONDA_HOME/conda-bld && \
    mkdir -p $HOME/.cache && \
    echo "export PYTHONPATH=${PYTHONPATH}:$HOME/open_ce" >> ${HOME}/.bashrc && \
    export PATH="/opt/rh/gcc-toolset-11/root/usr/bin:${PATH}" && \
    export GCC_11_HOME="/opt/rh/gcc-toolset-11/root/usr" && \
    echo "PATH="${PATH}"" >> ${HOME}/.profile && \
    echo "PATH="${PATH}"" >> ${HOME}/.bashrc && \
    echo "GCC_11_HOME="${GCC_11_HOME}"" >> ${HOME}/.bashrc && \
    chown -R ${BUILD_USER}:${CICD_GROUP} ${CONDA_HOME}

USER ${BUILD_USER}
RUN export PATH="/opt/rh/gcc-toolset-11/root/usr/bin:${PATH}" && \
    export GCC_11_HOME="/opt/rh/gcc-toolset-11/root/usr" && \
    echo "PATH="${PATH}"" >> ${HOME}/.profile && \
    echo "PATH="${PATH}"" >> ${HOME}/.bashrc && \
    echo "GCC_11_HOME="${GCC_11_HOME}"" >> ${HOME}/.bashrc && \
    mkdir -p $HOME/.cache && \
    echo ". $CONDA_HOME/etc/profile.d/conda.sh" >> ${HOME}/.bashrc && \
    echo "export PYTHONPATH=${PYTHONPATH}:$HOME/open_ce" >> ${HOME}/.bashrc && \
    echo "conda activate base" >> ${HOME}/.bashrc
