#!/usr/bin/env python
# *****************************************************************
# (C) Copyright IBM Corp. 2020, 2021. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# *****************************************************************

"""
This module simply calls open-ce's main function. It is essentially an alias for open-ce.
"""

import sys
import os
from importlib.util import spec_from_loader, module_from_spec
from importlib.machinery import SourceFileLoader

from open_ce.errors import OpenCEError

spec = spec_from_loader("opence", SourceFileLoader("opence",
           os.path.join(os.path.dirname(os.path.abspath(__file__)), 'open-ce')))
opence = module_from_spec(spec)
spec.loader.exec_module(opence)

def _main(arg_strings=None):
    #pylint: disable=protected-access
    opence._main(arg_strings)

if __name__ == '__main__':
    try:
        _main()
    except OpenCEError as err:
        print(err.msg, file=sys.stderr)
        sys.exit(1)

    sys.exit(0)
